/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_vackapi_jnilearn_JNILearn */

#ifndef _Included_org_vackapi_jnilearn_JNILearn
#define _Included_org_vackapi_jnilearn_JNILearn

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_vackapi_jnilearn_JNILearn
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_vackapi_jnilearn_JNILearn_test
  (JNIEnv *, jobject);

/*
 * Class:     org_vackapi_jnilearn_JNILearn
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_vackapi_jnilearn_JNILearn_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
